<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Admin zone - <?php echo $_SERVER['HTTP_HOST'] ?></title>
    <?php 
        $this->headLink()->appendStylesheet( $this->baseUrl() . '/css/admin/styles.css');
        $this->headLink()->appendStylesheet( $this->baseUrl() . '/css/jquery.fancybox-1.3.1.css');
        echo $this->headLink();
        echo $this->headScript()->appendFile( 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
        echo $this->headScript()->appendFile( $this->baseUrl() . '/js/jquery.fancybox-1.3.1.js');
    ?>
    <script type="text/javascript">
    $(document).ready( function(){
        $("a.fancybox").fancybox({
            'titleShow'    : false
        });
    });
    </script>
</head>
<body>
<div id="wrapper">

<?php include_once APPLICATION_PATH . '/views/scripts/admin/header.phtml'; ?>
<div id="content">
    <?php if (!empty($this->current_page_data['title'])): ?>
    <h1><?php echo $this->current_page_data['title'] ?></h1>
    <?php endif ?>
        
    <?php echo $this->layout()->content ?>
</div>

</div>
</body>
</html>
