<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Admin zone - <?php echo $_SERVER['HTTP_HOST'] ?></title>
    <?php 
        $this->headLink()->appendStylesheet( $this->baseUrl() . '/css/admin.css');
        echo $this->headLink();
    ?>
</head>
<body>
<div id="wrapper">

<div id="content">
    <?php echo $this->layout()->content ?>
</div>

</div>
</body>
</html>
