<div class="filter">
	<ul>
		<li class="active">
			<a href="">Favourite</a>
		</li>
		<li>
			<a href="">All</a>
		</li>
	</ul>
	<div class="clear"></div>
</div>

<div class="posts">
    <?php foreach ($this->posts as $post): ?>
    <div class="post">
    
        <h2><a href="<?php echo $post->link ?>"><?php echo $this->escape($post->title) ?></a></h2>
        
        <?php if ($post->is_favourite == 1): ?>
        <div class="favourite"></div>
        <?php endif ?>
        
  		<div class="text"><?php echo $post->text ?></div>
  		
  		<div class="info">
  		
  			<div class="date"><?php echo $post->date ?></div>
  			
	        <?php if (!empty($post->author)): ?>
	        <div class="author"><?php echo $this->escape($post->author) ?></div>
	        <?php endif ?>
  			
  			<div class="link">
  				<a href="<?php echo $post->link ?>"><?php echo $post->link ?></a>
  			</div>
  			
  		</div>
        
    </div>
    <?php endforeach ?>
</div>

