<div class="links">
	<ul>
		<li><a href="http://www.avalonsguide.com">www.avalonsguide.com</a> - Avalon's Guide: Emigrate to New Zealand</li>
		<li><a href="http://www.aucklanddailyphoto.com">www.aucklanddailyphoto.com</a> - The Auckland photography resource</li>
		<li><a href="http://move2nz.wordpress.com/">move2nz.wordpress.com</a> - Taking a good hard look at New Zealand Immigration issues</li>
	</ul>
</div>