<div class="text">

<h2>General</h2>

<p>At the moment in the Internet there are many web sites with materials about traveling, immigration and
living in New Zealand such as forums, standalone blogs, and informational sites. People who are always
interested in these topics have to regularly review all sites to find the information they need.</p>


<h2>Purpose</h2>

<p>The purpose of the project is to collect quality content about immigration to New Zealand from
different sources*, to organize it (with categories and tags) and give to users opportunity to search
needed information and to subscribe to common RSS. Additional purpose: to give opportunity to create
own content.</p>

<p><small>* Copyrights: the website will content only announces of materials from available sources (RSS etc.) and provide links to the
original</small></p>


<h2>Target Market Individuals</h2>

<p>The users, at the moment, are mainly Russian residents, based in Russia, Ukraine and other post-soviet
countries, who have interest and look for travel or immigration in New Zealand, and Russian immigrants
based in New Zealand who want to stay in touch with each other and to know latest news and events in
the Russian community.</p>

</div>