<div id="header">
    <div class="admin">
      Welcome <span class="username"><?php echo $this->user->name ?></span>
      <a class="logout" href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'logout'), null, true) ?>">Log out</a>
    </div>

    <div class="menu">
        <ul>
            <li<?php echo ($this->action=='index')?' class="active"':'';?>>
                <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=> 'index'), 'default', true) ?>">Posts</a>
            </li>
            <li<?php echo ($this->action=='links')?' class="active"':'';?>>
                <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=> 'index'), 'default', true) ?>">Links</a>
            </li>
            <li<?php echo ($this->action=='users')?' class="active"':'';?>>
                <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=> 'index'), 'default', true) ?>">Users</a>
            </li>
        </ul>
    </div>
</div>