<h1>Posts</h1>

<?php include_once APPLICATION_PATH . '/views/scripts/admin/search-bar.phtml'; ?>
<div class="posts list">
    <?php if (count($this->posts)):?>
    <table>
        <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Text</th>
            <th>Author</th>
            <th>Favourite</th>
            <th>Options</th>
        </tr>
        <?php $i=0; foreach ($this->posts as $post): $i++; ?>
        <tr class="<?php echo $i%2==0 ? 'odd' : 'even' ?>">
            <td class="date"><?php echo $post->date ?></td>
            <td><a href="<?php echo $post->link ?>"><?php echo html_entity_decode($post->title) ?></a></td>
            <td><?php echo html_entity_decode(substr(strip_tags($post->text), 0, 150)) ?>...</td>
            <td><?php echo $post->author ?></td>
            <td><?php echo $post->is_favourite ? 'yes' : 'no' ?></td>
            <td class="options">
                <a class="button" href="<?php echo $this->url(array('controller'=>'admin', 'action'=> 'postedit', 'post_id' => $post->id), 'default', true) ?>">Edit</a>
                <a class="button" href="<?php echo $this->url(array('controller'=>'admin', 'action'=> 'postdelete', 'post_id' => $post->id), 'default', true) ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php endif ?>
</div>